[package]
name = "coin98-starship"
version = "1.0.0"
authors = ["lukaz"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
anchor-lang = "0.24.2"
solana-program = "1.9.13"

[features]
cpi = ["no-entrypoint"]
default = []
no-entrypoint = []
no-idl = []

[lib]
name = "starship"
crate-type = ["cdylib", "lib"]

[profile.release]
overflow-checks = true
