name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Install Solana CLI
          run: sh -c "$(curl -sSfL https://release.solana.com/latest/install)"

        - name: Export path
          run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

        - name: Compile
          run: cargo build-sbf
          
        - name: Test
          run: cargo test-sbf