name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Install Rust
          uses: ATiltedTree/setup-rust@v1
          with:
            rust-version: 1.75.0

        - name: Install Solana CLI
          run: sh -c "$(curl -sSfL https://release.solana.com/1.16.1/install)"

        - name: Compile
          run: cargo-build-bpf

        - name: Test
          run: cargo test-bpf -- --nocapture