name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Setup Environment
          uses: metadaoproject/anchor-test@v2
          with:
            anchor-version: '0.28.0'
            solana-cli-version: '1.16.1'
            node-version: '16.15.1'

        - name: Compile
          run: anchor build

        - name: Test
          run: cargo test-bpf -- --nocapture