name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Install Solana CLI
          uses: metadaoproject/setup-solana@v1.0
          with: 
            solana-cli-version: '1.18.9'

        - name: Compile
          run: cargo build-sbf

        - name: Test
          run: cargo test-sbf -- --nocapture