name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Anchor Test
          uses: mrgnlabs/anchor-test-action@v0.4
          with:
            args: ""
            workspace_dir: "."