name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Install Solana CLI
        - uses: metadaoproject/anchor-test@v2
          with:
            anchor-version: '0.26.0'
            solana-cli-version: '1.16.17'
            node-version: '16.15.1'

        - name: Version
          run: |
            solana --version
            cargo --version

        - name: Compile
          run: cargo-build-bpf

        - name: Test
          run: cargo-test-bpf