name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Set up environment
          uses: metadaoproject/anchor-test@v2
          with:
            anchor-version: '0.28.0'
            solana-cli-version: '1.14.20'
            node-version: '16.15.1'

        - name: Build
          run: npm run build:rs
        
        - name: Test
          run: npm run test:rs