name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Install Rust
          run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

        - name: Install Solana CLI
          run: sh -c "$(curl -sSfL https://release.solana.com/1.16.27/install)"

        - name: Install anchor
          run: cargo install --git https://github.com/coral-xyz/anchor --tag v0.26.0 anchor-cli --locked

        - name: Compile
          run: anchor build

        - name: Test
          run: cargo test-bpf -- --nocapture